backend:
  name: github
  repo: amit-redkar/travelandcards
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

site_url: https://travelandcards.in
display_url: https://travelandcards.in

publish_mode: editorial_workflow
